$ANSIBLE_VAULT;1.1;AES256
38653138643661346565313530663830663166663130643438326131353361383064656235376234
3964666337353636663265626434666666336666333033630a376330613939376138323366326238
30386433303462636134323562623230613537373562623261363433366436383139306663616134
3838663866363337620a386637633631376335643733376163643639663565373466383234633861
34383864383832643033656637386663643433343066386434336536646239653930396637323530
3262386135356532356532623433616239376464363561303161
